name: Build and test
on:
  # Build PRs
  pull_request: ~
  # On push event
  push:
    # Build only changes pushed into the `master` branch.
    branches:
      - master
    # Ignore documentation changes (Netlify will handle this)
    paths-ignore:
      - 'docs/**'

jobs:
  build-and-test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        # Commenting Windows out in order to preserve our free minutes.
        # We can re-enable it, if we get a sponsor.
        #operating-system: [ubuntu-latest, windows-latest]
        operating-system: [ubuntu-latest]
        java: [ 8, 11.0.3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
#        run: mvn clean install -Pintegration-tests
        run: mvn clean install -Pjacoco-code-coverage

  sonarqube:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Commenting Windows out in order to preserve our free minutes.
        # We can re-enable it, if we get a sponsor.
        #operating-system: [ubuntu-latest, windows-latest]
        operating-system: [ubuntu-latest]
        java: [ 11.0.3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Analyze code and publish results to Sonarcloud
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn verify sonar:sonar -Pjacoco-code-coverage
